# =============================================
# Configuración de Base de Datos PostgreSQL
# =============================================
db.host=localhost
db.port=5432
db.name=7502510011_4_finanzas_banqueras
db.username=postgres
db.password=123

# =============================================
# Configuración SMTP (JavaMail)
# =============================================
smtp.host=smtp.gmail.com
smtp.port=587
smtp.username=raulberrioblanquicett07@gmail.com
smtp.password=osudyiblcetrtzlc
smtp.from.address=raulberrioblanquicett07@gmail.com
smtp.from.name=Finanzas_banqueras
